words = [
    "aiohttp",
    "aiter",
    "anext",
    "asctime",
    "asyncio",
    "clsx",
    "cov",
    "currentcolor",
    "dlx",
    "eastus",
    "fastapi",
    "figma",
    "grafana",
    "langchain",
    "langgraph",
    "legalscape",
    "levelname",
    "llm",
    "meiryo",
    "millis",
    "noqa",
    "noto",
    "nowait",
    "openai",
    "overscroll",
    "pinecone",
    "plc",
    "pnpm",
    "postgre",
    "psycopg",
    "pydantic",
    "pyright",
    "rerank",
    "reranked",
    "reranker",
    "reranking",
    "rustica",
    "saas",
    "scriptable",
    "slackmacgap",
    "starlette",
    "streamlit",
    "tinyspeck",
    "traceparent",
    "unfocus",
    "uvicorn",
    "videooff",
    "vitest",
    "wandh",
    "watsonb",
    "watsonc",
    "watsong",
    "wklr",
    "xlg",
    "yukima",
]
ignore_patterns = ['[\u3040-\u30FF\u4E00-\u9FFF]+']
